version: '3'

services: 
  gorocks:
    build:
      context: ./gorocks
      dockerfile: Dockerfile
    image: leooliveira1159/fullcycle
    container_name: gorocks
    networks:
      - gorocksnet
    ports:
      - "8080:80"

networks:
  gorocksnet:
    driver: bridge
